name: Deploy to EC2
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via AWS SSM
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Run deployment command
        run: |
          aws ssm send-command \
            --instance-ids "i-004968c1c4b6306c0" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["cd /home/ubuntu/shopping-app && git pull && sudo docker compose up -d --build"]'
